// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ePlhSZLnmzCXkWrPElCg2Wh6eTB9Vis',
    appId: '1:175115274593:web:84f2bf803f17aaf3939d20',
    messagingSenderId: '175115274593',
    projectId: 'temperatura-esp8266mod',
    authDomain: 'temperatura-esp8266mod.firebaseapp.com',
    databaseURL: 'https://temperatura-esp8266mod-default-rtdb.firebaseio.com',
    storageBucket: 'temperatura-esp8266mod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWl5tAqr5ne2xjXrZA06_I26pJdMBz1Gs',
    appId: '1:175115274593:android:2649212abc887350939d20',
    messagingSenderId: '175115274593',
    projectId: 'temperatura-esp8266mod',
    databaseURL: 'https://temperatura-esp8266mod-default-rtdb.firebaseio.com',
    storageBucket: 'temperatura-esp8266mod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0BQmjA-BJYFrpiNciyQ6V8RV5F0aMO8',
    appId: '1:175115274593:ios:1f975154456eb8a8939d20',
    messagingSenderId: '175115274593',
    projectId: 'temperatura-esp8266mod',
    databaseURL: 'https://temperatura-esp8266mod-default-rtdb.firebaseio.com',
    storageBucket: 'temperatura-esp8266mod.appspot.com',
    iosClientId: '175115274593-f8atvl2rugb0eg7h7ovjd96d8mvm7uad.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationEsp32Termometro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_0BQmjA-BJYFrpiNciyQ6V8RV5F0aMO8',
    appId: '1:175115274593:ios:1f975154456eb8a8939d20',
    messagingSenderId: '175115274593',
    projectId: 'temperatura-esp8266mod',
    databaseURL: 'https://temperatura-esp8266mod-default-rtdb.firebaseio.com',
    storageBucket: 'temperatura-esp8266mod.appspot.com',
    iosClientId: '175115274593-f8atvl2rugb0eg7h7ovjd96d8mvm7uad.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationEsp32Termometro',
  );
}
